package com.example.elementaryreading

enum class EveryLetter(val letter: String) {
    Letter0("A"),
    Letter1("Б"),
    Letter2("В"),
    Letter3("Г"),
    Letter4("Д"),
    Letter5("Е"),
    Letter6("Ё"),
    Letter7("Ж"),
    Letter8("З"),
    Letter9("И"),
    Letter10("Й"),
    Letter11("К"),
    Letter12("Л"),
    Letter13("М"),
    Letter14("Н"),
    Letter15("О"),
    Letter16("П"),
    Letter17("Р"),
    Letter18("С"),
    Letter19("Т"),
    Letter20("У"),
    Letter21("Ф"),
    Letter22("Х"),
    Letter23("Ц"),
    Letter24("Ч"),
    Letter25("Ш"),
    Letter26("Щ"),
    Letter27("Ь"),
    Letter28("Ы"),
    Letter29("Ъ"),
    Letter30("Э"),
    Letter31("Ю"),
    Letter32("Я")
}